var anObject = new Object();
console.log ('Value of anObject: ', anObject);
console.log ('Type of anObject: ', typeof(anObject));
var anArray = new Array();
console.log ('Value of anArray: ', anArray);
console.log ('Type of anArray: ', anArray);
var aFunction = new Function();
console.log ('Value of aFunction: ', aFunction);
console.log ('Type of aFunction: ', typeof(aFunction));
var aString = new String();
console.log ('Value of aString: ', aString);
console.log ('Type of aString: ', typeof(aString));
var aNumber = new Number();
console.log('Value of aNumber: ', aNumber);
console.log('Type of aNumber: ', typeof (aNumber));
var aBoolean = new Boolean();
console.log('Value of aBoolean: ', aBoolean);
console.log('Type of aBoolean: ', typeof (aBoolean));
